# Generated by Django 5.0.7 on 2024-08-05 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 21, 45, 4, 805290, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 12, 21, 45, 4, 804972, tzinfo=datetime.timezone.utc)),
        ),
    ]
