# Generated by Django 5.0.7 on 2024-08-05 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_survey_createdtime_alter_survey_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 21, 45, 24, 95175, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 12, 21, 45, 24, 94892, tzinfo=datetime.timezone.utc)),
        ),
    ]
