# Generated by Django 5.0.7 on 2024-07-30 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customuser_username_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('role_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roleId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
    ]
