# Generated by Django 5.0.7 on 2024-08-07 04:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_survey_description_alter_survey_createdtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='surveyId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 4, 41, 24, 94850, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 14, 4, 41, 24, 94572, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
