# Generated by Django 5.0.7 on 2024-07-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_role_alter_customuser_id_customuser_roleid'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
