# Generated by Django 5.0.7 on 2024-08-07 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_response_surveyid_alter_survey_createdtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyhistory',
            name='rewardStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 15, 9, 16, 20336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 14, 15, 9, 16, 20140, tzinfo=datetime.timezone.utc)),
        ),
    ]
