# Generated by Django 5.0.7 on 2024-07-30 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roleId',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
    ]
