# Generated by Django 5.0.7 on 2024-08-01 01:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_roleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('options', models.CharField(max_length=5000)),
                ('timeToComplete', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rewards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=400)),
                ('sector', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='response',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userResponse', models.CharField(max_length=500)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questions')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('rewardQuantity', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
                ('createdTime', models.DateTimeField(default=datetime.datetime(2024, 8, 1, 1, 25, 52, 363220, tzinfo=datetime.timezone.utc))),
                ('type', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.rewards')),
            ],
        ),
        migrations.CreateModel(
            name='surveyHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('surveyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.survey')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
