# Generated by Django 5.0.7 on 2024-08-07 16:16

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_surveyhistory_rewardstatus_alter_survey_createdtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='createdTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='survey',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 14, 16, 16, 14, 466911, tzinfo=datetime.timezone.utc)),
        ),
    ]
