# Generated by Django 5.0.7 on 2024-08-07 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_survey_createdtime_alter_survey_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 14, 16, 24, 3, 532983, tzinfo=datetime.timezone.utc)),
        ),
    ]
