# Generated by Django 5.0.7 on 2024-08-04 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_questions_rewards_company_response_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 10, 50, 59, 528828, tzinfo=datetime.timezone.utc)),
        ),
    ]
