# Generated by Django 5.0.7 on 2024-08-04 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customuser_last_name_alter_survey_createdtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 11, 4, 4, 254738, tzinfo=datetime.timezone.utc)),
        ),
    ]
